name: NSIS Test

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install NSIS
      run: choco install nsis

    - name: Build Installer
      run: makensis FikaFirewallFixer.nsi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FikaFirewallFixer
        path: FikaFirewallFixer.exe
